### ISSUE TITLE
Thread safety issues with OutputStream

### ISSUE THREAD

**Issue by robross0606** [christian-schlichtherle/truevfs#1]
Experiencing threading issues when attempting to get a TFileOutputStream:

`new TFileOutputStream(getFile(), FsAccessOption.CACHE, FsAccessOption.APPEND);`

```
net.java.truevfs.kernel.spec.FsSyncException: mscx:file:/C:/Users/Test/AppData/Local/Temp/c8fbb04a-ec18-469d-8aee-3bb19b1ca464.zip!/
        	at net.java.truevfs.kernel.impl.ResourceController$class.sync(ResourceController.scala:86)
        	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$CacheController$$super$sync(DefaultManager.scala:171)
        	at net.java.truevfs.kernel.impl.CacheController$class.sync(CacheController.scala:116)
        	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$SyncController$$super$sync(DefaultManager.scala:171)
        	at net.java.truevfs.kernel.impl.SyncController$class.doSync(SyncController.scala:172)
        	at net.java.truevfs.kernel.impl.SyncController$class.net$java$truevfs$kernel$impl$SyncController$$apply(SyncController.scala:134)
        	at net.java.truevfs.kernel.impl.SyncController$Output$1.stream(SyncController.scala:80)
        	at net.java.truevfs.kernel.impl.SyncController$Output$1.stream(SyncController.scala:74)
        	at net.java.truevfs.kernel.impl.LockController$Output$1$$anonfun$stream$2.apply(LockController.scala:81)
        	at net.java.truevfs.kernel.impl.LockController$Output$1$$anonfun$stream$2.apply(LockController.scala:81)
        	at net.java.truevfs.kernel.impl.LockingStrategy.apply(LockingStrategy.scala:78)
        	at net.java.truevfs.kernel.impl.LockController$Output$1.stream(LockController.scala:81)
        	at net.java.truevfs.kernel.impl.LockController$Output$1.stream(LockController.scala:75)
        	at net.java.truevfs.kernel.impl.FinalizeController$Output$1.stream(FinalizeController.scala:44)
        	at net.java.truevfs.kernel.impl.FinalizeController$Output$1.stream(FinalizeController.scala:40)
        	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$Output$1$$anonfun$stream$2.apply(FalsePositiveArchiveController.scala:119)
        	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$Output$1$$anonfun$stream$2.apply(FalsePositiveArchiveController.scala:119)
        	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$TryChild$.apply(FalsePositiveArchiveController.scala:195)
        	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.net$java$truevfs$kernel$impl$FalsePositiveArchiveController$$apply(FalsePositiveArchiveController.scala:172)
        	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController$Output$1.stream(FalsePositiveArchiveController.scala:119)
        	at net.java.truevfs.access.TFileOutputStream.<init>(TFileOutputStream.java:164)
        	at net.java.truevfs.access.TFileOutputStream.<init>(TFileOutputStream.java:149)
        	at cerdec.seams.dcams.core.io.commonsvfs.truevfs.zip.ZipFileObject.doGetOutputStream(ZipFileObject.java:188)
        	at org.apache.commons.vfs2.provider.AbstractFileObject.getOutputStream(AbstractFileObject.java:1399)
        	... 17 more
        	Suppressed: net.java.truevfs.kernel.impl.NeedsSyncException
        Caused by: net.java.truevfs.kernel.spec.FsOpenResourceException: Thread-local / total number of open I/O resources (e.g. streams or channels): 1 / 1
        	at net.java.truevfs.kernel.impl.ResourceController$class.sync(ResourceController.scala:77)
```

**Comment by robross0606** [comment]
Nevermind, I figured this out.
