### ISSUE TITLE
ServiceConfigurationError on JVM shutdown

### ISSUE THREAD

**Issue by dannyor** [christian-schlichtherle/truevfs#11]
My dependencies are:

> implementation("net.java.truevfs:truevfs-access:0.14.0")
implementation("net.java.truevfs:truevfs-kernel-impl:0.14.0")
implementation("net.java.truevfs:truevfs-driver-file:0.14.0")
implementation("net.java.truevfs:truevfs-driver-zip:0.14.0")

Using Oracle JDK 9.0.4

When JVM exits I get:
> Exception in thread "Thread-3" java.util.ServiceConfigurationError: No key manager available for class net.java.truecommons.key.spec.common.AesPbeParameters.
	at net.java.truecommons.key.spec.AbstractKeyManagerMap.manager(AbstractKeyManagerMap.java:36)
	at net.java.truevfs.comp.zipdriver.AbstractKeyController.keyManager(AbstractKeyController.java:153)
	at net.java.truevfs.comp.zipdriver.AbstractKeyController.sync(AbstractKeyController.java:149)
	at net.java.truevfs.kernel.spec.FsDelegatingController.sync(FsDelegatingController.java:122)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.sync(FalsePositiveArchiveController.java:236)
	at net.java.truevfs.kernel.spec.FsSync$1SyncVisitor.visit(FsSync.java:66)
	at net.java.truevfs.kernel.spec.FsSync$1SyncVisitor.visit(FsSync.java:59)
	at net.java.truevfs.kernel.impl.DefaultManager$3.call(DefaultManager.java:129)
	at net.java.truevfs.kernel.impl.DefaultManager.accept(DefaultManager.java:141)
	at net.java.truevfs.kernel.spec.FsSync.run(FsSync.java:77)
	at net.java.truevfs.kernel.impl.DefaultManager.lambda$new$0(DefaultManager.java:39)
	at net.java.truevfs.kernel.impl.ShutdownFuse.lambda$onDisarm$6(ShutdownFuse.java:64)
	at net.java.truevfs.kernel.impl.ShutdownFuse.onCondition(ShutdownFuse.java:72)
	at net.java.truevfs.kernel.impl.ShutdownFuse.onDisarm(ShutdownFuse.java:62)
	at net.java.truevfs.kernel.impl.ShutdownFuse.lambda$new$0(ShutdownFuse.java:36)
	at java.base/java.lang.Thread.run(Thread.java:844)

Besides that ugly error in the end, all seems to work fine

**Comment by christian-schlichtherle** [comment]
You're missing another dependency: https://search.maven.org/artifact/net.java.truecommons/truecommons-key-disable/2.5.0/jar

**Comment by christian-schlichtherle** [comment]
For a base list of dependencies, please refer to this POM: https://search.maven.org/artifact/net.java.truevfs/truevfs-profile-base/0.14.0/jar

**Comment by christian-schlichtherle** [comment]
Or, if you want to go "all-in", use these dependencies: https://search.maven.org/artifact/net.java.truevfs/truevfs-profile-full/0.14.0/jar

**Comment by dannyor** [comment]
You are the best!
Thanks for your wonderful and very usable library

**Comment by christian-schlichtherle** [comment]
You're welcome!
