### ISSUE TITLE
java.lang.NullPointerException: Deflater has been closed

### ISSUE THREAD

**Issue by jamieb22** [christian-schlichtherle/truevfs#2]
The only way to fix, is to restart entire JVM . 

017-11-13 09:43:29 5.c.s.a.ss [ERROR] failed to write attachment:Deflater has been closed
java.lang.NullPointerException: Deflater has been closed
at java.util.zip.Deflater.ensureOpen(Deflater.java:559)
at java.util.zip.Deflater.getBytesRead(Deflater.java:485)
at net.java.truevfs.comp.zip.AbstractZipOutputStream$DeflaterOutputMethod.finish(AbstractZipOutputStream.java:1020)
at net.java.truevfs.comp.zip.AbstractZipOutputStream$Crc32UpdatingOutputMethod.finish(AbstractZipOutputStream.java:1073)
at net.java.truevfs.comp.zip.AbstractZipOutputStream.closeEntry(AbstractZipOutputStream.java:463)
at net.java.truevfs.comp.zip.AbstractZipOutputStream.finish(AbstractZipOutputStream.java:491)
at net.java.truevfs.comp.zipdriver.ZipOutputService.close(ZipOutputService.java:240)
at net.java.truevfs.kernel.spec.cio.MultiplexingOutputService.close(MultiplexingOutputService.java:155)
at net.java.truecommons.cio.DecoratingOutputService.close(DecoratingOutputService.java:32)
at net.java.truevfs.kernel.impl.DisconnectingOutputService.net$java$truevfs$kernel$impl$CheckedCloseable$$super$close(DisconnectingOutputService.scala:28)
at net.java.truevfs.kernel.impl.CheckedCloseable$class.close(CheckedCloseable.scala:26)
at net.java.truevfs.kernel.impl.DisconnectingOutputService.close(DisconnectingOutputService.scala:28)
at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply$mcV$sp(LockOutputService.scala:30)
at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
at net.java.truevfs.kernel.impl.LockOn$.apply(LockOn.scala:23)
at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
at net.java.truevfs.kernel.impl.LockOutputService.close(LockOutputService.scala:30)
at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:351)
at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:349)
at scala.Option.foreach(Option.scala:257)
at net.java.truevfs.kernel.impl.TargetArchiveController.close(TargetArchiveController.scala:349)
at net.java.truevfs.kernel.impl.TargetArchiveController.sync(TargetArchiveController.scala:253)
at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$ResourceController$$super$sync(DefaultManager.scala:173)
at net.java.truevfs.kernel.impl.ResourceController$class.sync(ResourceController.scala:70)
at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$CacheController$$super$sync(DefaultManager.scala:173)
at net.java.truevfs.kernel.impl.CacheController$class.sync(CacheController.scala:116)
at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$SyncController$$super$sync(DefaultManager.scala:173)
at net.java.truevfs.kernel.impl.SyncController$class.doSync(SyncController.scala:172)
at net.java.truevfs.kernel.impl.SyncController$class.sync(SyncController.scala:149)
at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$LockController$$super$sync(DefaultManager.scala:173)
at net.java.truevfs.kernel.impl.LockController$$anonfun$sync$1.apply$mcV$sp(LockController.scala:96)
at net.java.truevfs.kernel.impl.LockController$$anonfun$sync$1.apply(LockController.scala:96)
at net.java.truevfs.kernel.impl.LockController$$anonfun$sync$1.apply(LockController.scala:96)
at net.java.truevfs.kernel.impl.LockingStrategy.apply(LockingStrategy.scala:78)
at net.java.truevfs.kernel.impl.LockController$class.sync(LockController.scala:96)
at net.java.truevfs.kernel.impl.DefaultManager$BackController.sync(DefaultManager.scala:173)
at net.java.truevfs.kernel.impl.ArchiveControllerAdapter.sync(ArchiveControllerAdapter.scala:36)
at net.java.truevfs.kernel.spec.FsDecoratingController.sync(FsDecoratingController.java:117)
at net.java.truevfs.kernel.spec.FsDecoratingController.sync(FsDecoratingController.java:117)
at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.sync(FalsePositiveArchiveController.scala:157)
at net.java.truevfs.kernel.spec.FsSync$1SyncVisitor.visit(FsSync.java:71)
at net.java.truevfs.kernel.spec.FsSync$1SyncVisitor.visit(FsSync.java:64)
at net.java.truevfs.kernel.impl.DefaultManager$$anonfun$accept$2.apply(DefaultManager.scala:93)
at net.java.truevfs.kernel.impl.DefaultManager$$anonfun$accept$2.apply(DefaultManager.scala:91)
at scala.collection.Iterator$class.foreach(Iterator.scala:750)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
at net.java.truevfs.kernel.impl.DefaultManager$withFilter.accept(DefaultManager.scala:112)
at net.java.truevfs.kernel.impl.DefaultManager.accept(DefaultManager.scala:91)
at net.java.truevfs.kernel.spec.FsSync.run(FsSync.java:82)
at net.java.truevfs.ext.pacemaker.PaceManager.unmountEvictedArchiveFileSystems(PaceManager.scala:56)
at net.java.truevfs.ext.pacemaker.PaceManager.recordAccess(PaceManager.scala:39)
at net.java.truevfs.ext.pacemaker.PaceController$$anonfun$apply$1.apply$mcV$sp(PaceController.scala:25)
at net.java.truevfs.ext.pacemaker.PaceController$$anonfun$apply$1.apply(PaceController.scala:25)
at net.java.truevfs.ext.pacemaker.PaceController$$anonfun$apply$1.apply(PaceController.scala:25)
at net.java.truecommons.shed.OnTryFinally$OnTryStatement.onFinally(OnTryFinally.scala:64)
at net.java.truevfs.ext.pacemaker.PaceController.apply(PaceController.scala:24)
at net.java.truevfs.ext.pacemaker.AspectController$Output.stream(AspectController.scala:67)
at net.java.truevfs.access.TFileOutputStream.(TFileOutputStream.java:164)
at net.java.truevfs.access.TFileOutputStream.(TFileOutputStream.java:134)
at net.java.truevfs.access.TFileOutputStream.(TFileOutputStream.java:120)

**Comment by christian-schlichtherle** [comment]
I'm sorry for the late response, notifications for this project have been accidentally shut off.

Does this issue still apply to TrueVFS 0.12.2 and how can I reproduce it?
